# Generated by Django 3.2.14 on 2022-07-18 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('loginCnt', models.IntegerField(default=0)),
                ('lookYn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
                ('imgPath', models.CharField(blank=True, max_length=500)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('user_id', models.CharField(blank=True, max_length=500)),
                ('user_pwd', models.CharField(blank=True, max_length=500)),
                ('qtitle', models.CharField(blank=True, max_length=500)),
                ('qcontent', models.CharField(blank=True, max_length=5000)),
                ('qtag', models.CharField(blank=True, max_length=500)),
                ('stackoverflow', models.CharField(blank=True, max_length=500)),
                ('serverfault', models.CharField(blank=True, max_length=500)),
                ('superuser', models.CharField(blank=True, max_length=500)),
                ('askubuntu', models.CharField(blank=True, max_length=500)),
                ('askdifferent', models.CharField(blank=True, max_length=500)),
                ('writer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='BoardApp.user')),
            ],
        ),
    ]
